### Récupération des listes
GET http://localhost:5050/lists

### Récupération d'une liste
GET http://localhost:5050/lists/1

### création d'une liste
POST http://localhost:5050/lists
Content-Type: application/x-www-form-urlencoded

name=liste test post
&position=1


### création d'une liste
PATCH http://localhost:5050/lists/1
Content-Type: application/x-www-form-urlencoded

name=<img src="ImageNonFonctionnelle.png" onerror="alert('Hahahaha je suis le pirate !!!')">
&position=15

### suppression d'une liste
DELETE http://localhost:5050/lists/3